<?php

if (!defined('ABSPATH')) {
	exit; // Exit if accessed directly.
}

/**
 * admin\Import\st_import_data class
 *
 * @package streamit
 */

class st_import_data
{
	/**
	 * Gets the unique identifier for the theme component.
	 *
	 * @return string Component slug.
	 */

	public function get_slug(): string
	{
		return 'import';
	}

	/**
	 * Adds the action and filter hooks to integrate with WordPress.
	 */

	public function __construct()
	{

		add_filter('merlin_generate_child_functions_php', 	array($this, 'st_generate_child_functions_php'), 10, 2);
		add_filter('merlin_generate_child_style_css', 		array($this, 'st_generate_child_style_css'), 10, 5);
		add_filter('merlin_import_files', 					array($this, 'st_import_files'));
		add_action('merlin_after_all_import', 				array($this, 'st_after_import_setup'));
		add_filter('merlin_generate_child_screenshot', 		array($this, 'st_generate_child_screenshot'));
	}

	public function st_generate_child_functions_php($output, $slug)
	{

		$slug_no_hyphens = strtolower(preg_replace('#[^a-zA-Z]#', '', $slug));

		$output = "
		<?php
		/**
		 * Theme functions and definitions.
		 */
		add_action( 'wp_enqueue_scripts', '{$slug_no_hyphens}_enqueue_styles' ,99);

		function {$slug_no_hyphens}_enqueue_styles() {
				
			wp_enqueue_style( 'parent-style', get_stylesheet_directory_uri() . '/style.css'); 
			wp_enqueue_style( 'child-style',get_stylesheet_directory_uri() . '/style.css');
		}

		/**
		 * Set up My Child Theme's textdomain.
		*
		* Declare textdomain for this child theme.
		* Translations can be added to the /languages/ directory.
		*/
		function {$slug_no_hyphens}_child_theme_setup() {
			load_child_theme_textdomain( 'streamit', get_stylesheet_directory() . '/languages' );
		}
		add_action( 'after_setup_theme', '{$slug_no_hyphens}_child_theme_setup' );
	";

		// Let's remove the tabs so that it displays nicely.
		$output = trim(preg_replace('/\t+/', '', $output));

		// Filterable return.
		return $output;
	}

	public function st_generate_child_style_css($output, $slug, $author, $parent, $version)
	{

		$output = "
			/**
			* Theme Name: {$parent} Child
			* Description: This is a child theme of {$parent}, generated by iQonic Design.
			* Author: {$author}
			* Template: {$slug}
			* Version: {$version}
			*/\n
		";

		// Let's remove the tabs so that it displays nicely.
		$output = trim(preg_replace('/\t+/', '', $output));

		return  $output;
	}

	public function st_import_files()
	{
		return array(
			array(
				'import_file_name'             => esc_html__('All Content', 'streamit'),
				'local_import_file'            => trailingslashit(get_template_directory()) . 'admin/import/Demo/streamit-content.xml',
				'local_import_widget_file'     => trailingslashit(get_template_directory()) . 'admin/import/Demo/streamit-widget.wie',
				'local_import_customizer_file' => trailingslashit(get_template_directory()) . 'admin/import/Demo/streamit-export.dat',
				'local_import_redux'           => array(
					array(
						'file_path'   => trailingslashit(get_template_directory()) . 'admin/import/Demo/streamit-redux.json',
						'option_name' => 'streamit_options',
					),
				),
				'import_preview_image_url'     => get_template_directory_uri() . '/screenshot.png',
				'import_notice' 			   => esc_html__('DEMO IMPORT REQUIREMENTS: Memory Limit of 128 MB and max execution time (php time limit) of 300 seconds. ', 'streamit') . '</br></br>' . esc_html__('Based on your INTERNET SPEED it could take 5 to 25 minutes. ', 'streamit'),
				'preview_url'                  => 'https://streamit-wordpress.iqonic.design',
			),
		);
	}

	public function st_after_import_setup()
	{
		global $wp_filesystem;

		$content = '';

		// Assign menus to their locations.
		$menus     = wp_get_nav_menus();
		$locations = get_theme_mod('nav_menu_locations');

		if ($menus) {
			foreach ($menus as $menu) {
				if ($menu->name == 'Main Menu') {
					$locations['primary'] = $menu->term_id;
				}
			}
		}
		set_theme_mod('nav_menu_locations', $locations); // set menus to locations 

		//Save menus
		$this->save_menus();

		//reading settings default static pages
		$front_page_id = get_page_by_path('OTT Home');
		$blog_page_id  = get_page_by_path('Blog');

		update_option('show_on_front', 'page');
		update_option('page_on_front', $front_page_id->ID);
		update_option('page_for_posts', $blog_page_id->ID);

		//updates quick view icon
		update_option('woosq_button_type', 'link');
		update_option('woosq_button_position', '0');


		//replace custome link
		$this->replace_custom_link();

		$this->replace_footer_custom_link();

		//change woocommerce default shop page
		$id = get_page_by_path('shop-2');
		if ($id) {
			$id = $id->ID;
			update_option('woocommerce_shop_page_id', $id);
		}

		$checkout_page = get_page_by_path('checkout-2');
		if ($checkout_page) {
			$checkout_page_id = $checkout_page->ID;
			// Update WooCommerce setting for the Checkout page
			update_option('woocommerce_checkout_page_id', $checkout_page_id);
		}

		//change wishlist page
		$wishlist_page = get_page_by_path('wishlist-2');
		if ($wishlist_page) {
			$wishlist_page_id = $wishlist_page->ID;
			// Update YITH Wishlist page option
			update_option('yith_wcwl_wishlist_page_id', $wishlist_page_id);
			// Ensure the YITH plugin settings are refreshed
			do_action('yith_wcwl_after_wishlist_page_set', $wishlist_page_id);
			update_option('yith_wcwl_add_to_wishlist_text', '');
		}

		// Import Elementor settings
		$import_file = trailingslashit(get_template_directory()) . 'admin/import/Demo/elementor-site-settings.json';

		if (file_exists($import_file)) {
			global $wp_filesystem;

			// Initialize the WordPress filesystem
			if (empty($wp_filesystem)) {
				require_once ABSPATH . '/wp-admin/includes/file.php';
				WP_Filesystem();
			}

			// Read the contents of the file
			$content = $wp_filesystem->get_contents($import_file);

			if (!empty($content)) {
				// Decode the JSON content
				$site_settings = json_decode($content, true);

				if (is_array($site_settings)) {
					// Get the active Elementor kit ID
					$default_post_id = get_option('elementor_active_kit');

					if (!empty($default_post_id)) {
						// Update Elementor site settings
						update_post_meta($default_post_id, '_elementor_page_settings', $site_settings);
						error_log('Elementor site settings have been successfully imported.');
					} else {
						error_log('No active Elementor kit found.');
					}
				} else {
					error_log('Failed to decode the site settings JSON.');
				}
			} else {
				error_log('The site settings file is empty.');
			}
		} else {
			error_log('The site settings file does not exist.');
		}

		// Retrieve existing settings or initialize as an empty array if not found
		$this->quick_view_options();



		//Elementor post-types settings for edit with elementor option
		$enable_edit_with_elementor = [
			"post",
			"page",
		];
		update_option('elementor_cpt_support', $enable_edit_with_elementor);

		// save woof setting
		$woof_setting_file =  trailingslashit(get_template_directory()) . 'admin/import/Demo/streamit-woof-setting.json';
		if (file_exists($woof_setting_file)) {
			$content =  $wp_filesystem->get_contents($woof_setting_file);
			if (!empty($content)) {
				$woof_options = json_decode($content, true);
				foreach ($woof_options as $option_name => $option_data) {
					if (is_serialized($option_data)) {
						$option_data = unserialize($option_data);
					}
					update_option($option_name, $option_data);
				}
			}
		}

		// Update the permalink structure
		update_option('permalink_structure', '/%postname%/');
		flush_rewrite_rules();

		//REGISTERS 3 DEFAULT PLAN FOR PMP
		$this->register_default_pmp_plans();

		//GENERATE PMPRO PAGES
		$this->generate_default_pmpro_pages();
		

		//To clear Elementor cache after import
		if (
			class_exists('\Elementor\Plugin') &&
			isset(\Elementor\Plugin::$instance) &&
			isset(\Elementor\Plugin::$instance->files_manager)
		) {
			\Elementor\Plugin::$instance->files_manager->clear_cache();
		}

	}

	public function quick_view_options()
	{
		$options = get_option('woosq_settings', array());

		// Ensure the settings array is properly initialized
		if (is_array($options)) {
			// Update the specific quick view options
			$options['button_type'] = 'link'; // Set button type to 'link'
			$options['button_icon'] = 'only'; // Set button icon to 'only'

			// Save the updated options back to the database
			update_option('woosq_settings', $options);
		}
	}

	public function replace_custom_link()
	{
		//change menu custom link
		$old_domain = 'https://streamit-wordpress.iqonic.design';
		$new_domain = home_url();

		// Define the menu slug.
		$menu_name = 'main-menu'; // Replace with your menu slug.

		// Get the menu object by slug.
		$menu = wp_get_nav_menu_object($menu_name);

		// Check if the menu exists.
		if (!$menu) {
			error_log('Menu not found with slug: ' . $menu_name);
			return;
		}

		// Get the menu ID and items.
		$menu_id = $menu->term_id;
		$menu_items = wp_get_nav_menu_items($menu_id);

		// Check if there are menu items.
		if (!empty($menu_items)) {
			foreach ($menu_items as $menu_item) {
				// Check if it's a custom link and starts with the old domain.
				if ($menu_item->type === 'custom' && strpos($menu_item->url, $old_domain) === 0) {
					// Extract the path after the old domain.
					$path = str_replace($old_domain, '', $menu_item->url);

					// Create the new URL by appending the path to the new domain.
					$new_url = trailingslashit($new_domain) . ltrim($path, '/');

					// Update the menu item's URL only.
					wp_update_nav_menu_item($menu_id, $menu_item->ID, [
						'menu-item-object-id' => $menu_item->object_id,
						'menu-item-parent-id' => $menu_item->menu_item_parent,
						'menu-item-db-id'     => $menu_item->ID,
						'menu-item-object'    => $menu_item->object,
						'menu-item-type'      => $menu_item->type,
						'menu-item-url'       => esc_url($new_url),
						'menu-item-title'     => $menu_item->title,
						'menu-item-status'    => $menu_item->post_status,
					]);
				}
			}
		} else {
			error_log('No menu items found for menu ID: ' . $menu_id);
		}
	}

	public function replace_footer_custom_link()
	{
		//change menu custom link
		$old_domain = 'https://streamit-wordpress.iqonic.design';
		$new_domain = home_url();

		// Define the menu slug.
		$menu_name = 'footer-movies-to-watch'; // Replace with your menu slug.

		// Get the menu object by slug.
		$menu = wp_get_nav_menu_object($menu_name);

		// Check if the menu exists.
		if (!$menu) {
			error_log('Menu not found with slug: ' . $menu_name);
			return;
		}

		// Get the menu ID and items.
		$menu_id = $menu->term_id;
		$menu_items = wp_get_nav_menu_items($menu_id);


		// Check if there are menu items.
		if (!empty($menu_items)) {
			foreach ($menu_items as $menu_item) {
				// Check if it's a custom link and starts with the old domain.
				if ($menu_item->type === 'custom' && strpos($menu_item->url, $old_domain) === 0) {
					// Extract the path after the old domain.
					$path = str_replace($old_domain, '', $menu_item->url);

					// Create the new URL by appending the path to the new domain.
					$new_url = trailingslashit($new_domain) . ltrim($path, '/');

					// Update the menu item's URL only.
					wp_update_nav_menu_item($menu_id, $menu_item->ID, [
						'menu-item-object-id' => $menu_item->object_id,
						'menu-item-parent-id' => $menu_item->menu_item_parent,
						'menu-item-db-id'     => $menu_item->ID,
						'menu-item-object'    => $menu_item->object,
						'menu-item-type'      => $menu_item->type,
						'menu-item-url'       => esc_url($new_url),
						'menu-item-title'     => $menu_item->title,
						'menu-item-status'    => $menu_item->post_status,
					]);
				}
			}
		} else {
			error_log('No menu items found for menu ID: ' . $menu_id);
		}
	}

	public function register_default_pmp_plans()
	{
		if(!function_exists('pmpro_sort_levels_by_order')) return;
 		global $wpdb;

		$pmpro_levels = pmpro_sort_levels_by_order(pmpro_getAllLevels(true, false));
		$existing_ids = array_column($pmpro_levels, 'id'); // Get all existing plan IDs

		$default_pmpro_levels = [
			[
				'id' 				=> 2,
				'name' 				=> "Basic Plan",
				'description' 		=> "",
				'confirmation'		=> "",
				'initial_payment' 	=> 0,
				'billing_amount' 	=> 0,
				'cycle_number' 		=> 0,
				'cycle_period' 		=> "Day",
			],
			[
				'id' 				=> 3,
				'name' 				=> "Standard Plan",
				'description' 		=> "",
				'confirmation'		=> "",
				'initial_payment' 	=> 19,
				'billing_amount' 	=> 19,
				'cycle_number' 		=> 1,
				'cycle_period' 		=> "Month",
			],
			[
				'id' 				=> 4,
				'name' 				=> "Premium Plan",
				'description' 		=> "Enjoy all the benefits of Streamit",
				'confirmation'		=> "",
				'initial_payment' 	=> 39,
				'billing_amount' 	=> 39,
				'cycle_number' 		=> 3,
				'cycle_period' 		=> "Month",
			],
		];

		foreach ($default_pmpro_levels as $pmp_plan) {
			if (in_array($pmp_plan['id'], $existing_ids)) continue; // Skip if plan already exists

			$register_default_pmp_plans = [
				'id' 				=> $pmp_plan['id'],
				'name' 				=> $pmp_plan['name'],
				'description' 		=> $pmp_plan['description'],
				'confirmation' 		=> $pmp_plan['confirmation'],
				'initial_payment' 	=> $pmp_plan['initial_payment'],
				'billing_amount' 	=> $pmp_plan['billing_amount'],
				'cycle_number' 		=> $pmp_plan['cycle_number'],
				'cycle_period' 		=> $pmp_plan['cycle_period'],
				'billing_limit' 	=> 0,
				'trial_amount' 		=> 0,
				'trial_limit' 		=> 0,
				'expiration_number' => 0,
				'expiration_period' => '',
				'allow_signups' 	=> 1 // Set this correctly
			];

			$wpdb->insert(
				$wpdb->prefix . 'pmpro_membership_levels', // Ensure correct table prefix
				$register_default_pmp_plans,
				[
					'%d',
					'%s',
					'%s',
					'%s',
					'%f',
					'%f',
					'%d',
					'%s',
					'%d',
					'%f',
					'%d',
					'%d',
					'%s',
					'%d'
				]
			);
		}
	}

	public function generate_default_pmpro_pages()
	{
		global $wpdb;

		if (function_exists('pmpro_setOption')) {
			$generate_pmpro_pages = [
				'account' => [
					esc_html__('Membership Account', 'streamit'),
					'membership-account'
				],
				'billing' => [
					esc_html__('Membership Billing', 'streamit'),
					'membership-billing'
				],
				'cancel' => [
					esc_html__('Membership Cancel', 'streamit'),
					'membership-cancel',
				],
				'checkout' => [
					esc_html__('Membership Checkout', 'streamit'),
					'membership-checkout',
				],
				'confirmation' => [
					esc_html__('Membership Confirmation', 'streamit'),
					'membership-confirmation',
				],
				'invoice' => [
					esc_html__('Membership Invoice', 'streamit'),
					'membership-invoice',
				],
				'levels' => [
					esc_html__('Membership Levels', 'streamit'),
					'pricing-plan',
				],
				'login' => [
					esc_html__('Log In', 'streamit'),
					'login',
				],
				'member_profile_edit' => [
					esc_html__('Your Profile', 'streamit'),
					'your-profile',
				],
			];

			$pages = array();

			foreach ($generate_pmpro_pages as $key => $pmpro_pages) {
				$pmpro_page = $pmpro_pages[1];

				if (!empty($pmpro_page)) {
					// Prepare and execute the query securely
					$sql = $wpdb->prepare(
						"SELECT ID, post_name, post_parent, post_type
                    FROM $wpdb->posts
                    WHERE post_name = %s
                    AND post_type IN ('page', 'attachment')",
						$pmpro_page
					);

					$pages[$key] = $wpdb->get_results($sql, OBJECT);
				}
			}

			foreach ($pages as $key => $pmpro_pages) {
				$key_exists = pmpro_getOption($key . '_page_id');

				if (empty($key_exists) && !empty($pmpro_pages[0]->ID)) {
					pmpro_setOption($key . '_page_id', $pmpro_pages[0]->ID);
				}
			}
		}
	}

	public function st_generate_child_screenshot()
	{
		return trailingslashit(get_template_directory()) . 'screenshot.png';
	}

	public function save_menus()
	{
		$menu_item = get_posts([
			'post_type' => 'nav_menu_item',
			'post_status' => 'publish',
			'numberposts' => -1,
		]);
		foreach ($menu_item as $key => $value) {
			wp_update_post(
				array(
					'ID' => $value->ID,
					'post_content' => $value->post_content,
				)
			);
		}
	}
}

new st_import_data();
